services:
  db:
    image: mariadb:10.6
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
    volumes:
      - ./docker/matomo-db:/var/lib/mysql

  matomo:
    image: matomo:5-fpm-alpine
    links:
      - db
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=password
      - MATOMO_DATABASE_DBNAME=matomo
    volumes:
      - ./:/var/www/html/plugins/FunnelInsights
      - ./docker/config/config.ini.php:/var/www/html/config/config.ini.php

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    links:
      - matomo
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/plugins/FunnelInsights
